import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  
        
        `}
      >  <div className="luxury-bg">
      <div className="stars"></div>
      <div className="boxes">
        <span className="box b1"></span>
        <span className="box b2"></span>
        <span className="box b3"></span>
      </div>
    </div>
    <div className="content">

        {children}
    </div>
      </body>
    </html>
  );
}
